/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_extropies_ewalletutil_EWalletUtil */

#ifndef _Included_com_extropies_ewalletutil_EWalletUtil
#define _Included_com_extropies_ewalletutil_EWalletUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_ALL
#define com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_ALL 0L
#undef com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_1
#define com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_1 1L
#undef com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_2
#define com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_2 2L
#undef com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_3
#define com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_3 3L
#undef com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_4
#define com_extropies_ewalletutil_EWalletUtil_EOS_SER_PART_4 4L
/*
 * Class:     com_extropies_ewalletutil_EWalletUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_extropies_ewalletutil_EWalletUtil_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_extropies_ewalletutil_EWalletUtil
 * Method:    PAEW_EOS_TX_Serialize
 * Signature: (Ljava/lang/String;[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_extropies_ewalletutil_EWalletUtil_PAEW_1EOS_1TX_1Serialize
  (JNIEnv *, jclass, jstring, jbyteArray, jintArray);

/*
 * Class:     com_extropies_ewalletutil_EWalletUtil
 * Method:    PAEW_EOS_TX_Serialize_part
 * Signature: (Ljava/lang/String;I[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_extropies_ewalletutil_EWalletUtil_PAEW_1EOS_1TX_1Serialize_1part
  (JNIEnv *, jclass, jstring, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
